### ISSUE TITLE
v1.4.0 drops support for node.js v0.10 and v0.12

### ISSUE THREAD

**Issue by bnoordhuis** [bcoe/optional-dev-dependency#16]
Commit b9c78d7 introduces ES6 code that makes it impossible to use this module with node.js v0.10 and v0.12.  It also removes CI coverage for those versions so it looks like the change was intentional.

That would be perfectly acceptable if it had been published as v2.0.0 but because it's a minor release, it breaks the build for people that diligently put `"optional-dev-dependency": "^1.0.0"` in their package.json.

No action required - reverting and publishing v1.4.1 or v1.5.0 would be a semver violation too, if I read the changelog right - but perhaps it's something you can keep in mind next time.

**Comment by hildjj** [comment]
ack.  Sorry for that.  Let me know if there's anything I can do to help; for instance, I would be willing to back-port a 0.10 version if needed.

**Comment by bcoe** [comment]
@hildjj when you get a second, perhaps just unpublish `1.4.0`, so that folks get the prior release. And publish republish as `2.0`?

**Comment by bcoe** [comment]
@hildjj or I'm also comfortable with no action, since no one has complained in the two weeks that this has been out.

**Comment by hildjj** [comment]
@bcoe I'm ok with close, and we'll fix it if anyone complains.

**Comment by sam-github** [comment]
Its not strictly true that no one has complained, we did :-). Its possible others just pinned to an older version and didn't bother reporting. But I can understand taking a "wait and see" approach here.

**Comment by hildjj** [comment]
@sam-github, @bnoordhuis, if either of you is actually using this package, and it's causing you any pain at all, I'll do the fix.

**Comment by bcoe** [comment]
@sam-github, @bnoordhuis if this is tripping you up, let's revert the `1.4.0` release 👍 

@hildjj I think all you'd need to do is unpublish `1.4.0`, we should make appropriate edits to the CHANGELOG.md, however.

**Comment by hildjj** [comment]
1.4 unpublished.  Working on a 2.0

**Comment by hildjj** [comment]
Should I update dependencies (for cross-spawn in particular) while I'm at it? :)

**Comment by hildjj** [comment]
waiting on a LGTM from @bcoe.
